---
title: "Darwin Core mapping"
subtitle: "For: dwc:event workshop: camera trapping data"
author:
- Lien Reyserhove
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float: true
---

Install packages

```{r}
#install.packages("frictionless")
#devtools::install_github("inbo/camtraptor")
#devtools::install("../camtrapdp/")
```

Load packages

```{r}
library(frictionless)
library(camtraptor)
library(camtrapdp)
library(tidyverse)
library(here)
```

# Camera Trap Data Package

```{r}
camtrapDP <- example_dataset()

deployments <- read_resource(camtrapDP, "deployments")
observations <- read_resource(camtrapDP, "observations")
media <- read_resource(camtrapDP, "media")
```

Export data:

```{r}
write_csv(deployments, here("data", "camtrap_dp", "deployments.csv"), na = "")
write_csv(observations, here("data", "camtrap_dp", "observations.csv"), na = "")
write_csv(media, here("data", "camtrap_dp", "media.csv"), na = "")
```



# DwC - Occurrence Core mapping

Write to Darwin Core:

```{r}
write_dwc(x = camtrapDP, directory = "./data/dwc_occurrence/")
```

# DwC - Event Core mapping

## Event Core

```{r}
# Create parent events (deployment) mapping

parent_event <- 
  deployments %>% mutate(
    .keep = "none",
    eventID = deploymentID,
    parentEventID = "",
    eventType = "deployment",
    eventDate = glue::glue(
      "{start}/{end}",
      start = format(.data$deploymentStart, format = "%Y-%m-%dT%H:%M:%SZ"),
      end = format(.data$deploymentEnd, format = "%Y-%m-%dT%H:%M:%SZ")),
    habitat = .data$habitat,
    samplingProtocol = "camera trap",
    decimalLatitude = .data$latitude,
    decimalLongitude = .data$longitude,
    geodeticDatum = "EPSG:4326",
    coordinateUncertaintyInMeters = .data$coordinateUncertainty,
    locationID = .data$locationID,
    locationName = .data$locationName)

# Create events (sequence) mapping

event <- 
  observations %>% 
    filter(observationLevel == "event"
    ) %>% 
  left_join(
    select(deployments, deploymentID, latitude, longitude, coordinateUncertainty,locationID, locationName, habitat),
    by = "deploymentID") %>% 
    dplyr::mutate(
      .keep = "none",
      eventID = .data$eventID,
      parentEventID = .data$deploymentID,
      eventType = "sequence",
      eventDate = glue::glue(
       "{start}/{end}",
        start = format(.data$eventStart, format = "%Y-%m-%dT%H:%M:%SZ"),
        end = format(.data$eventEnd, format = "%Y-%m-%dT%H:%M:%SZ")),
      habitat = .data$habitat,
      samplingProtocol = "camera trap",
      decimalLatitude = .data$latitude,
      decimalLongitude = .data$longitude,
      geodeticDatum = "EPSG:4326",
      coordinateUncertaintyInMeters = .data$coordinateUncertainty,
      locationID = .data$locationID,
      locationName = .data$locationName)

# Create child events (media-based observations) mapping

child_1 <-
  observations %>% 
    filter(observationLevel == "media"
    ) %>% 
    left_join(
    select(deployments, deploymentID, latitude, longitude, coordinateUncertainty,locationID, locationName, habitat),
    by = "deploymentID") %>% 
    dplyr::mutate(
      .keep = "none",
      eventID = .data$mediaID,
      parentEventID = .data$eventID,
      eventType = "media",
      eventDate = format(.data$eventStart, format = "%Y-%m-%dT%H:%M:%SZ"),
      habitat = .data$habitat,
      samplingProtocol = "camera trap",
      decimalLatitude = .data$latitude,
      decimalLongitude = .data$longitude,
      geodeticDatum = "EPSG:4326",
      coordinateUncertaintyInMeters = .data$coordinateUncertainty,
      locationID = .data$locationID,
      locationName = .data$locationName)

# Create Event Core:

dwc_event <- bind_rows(parent_event, event, child_1) %>% 
  mutate( 
    type = "Event",
    rightsHolder = "Research Institute for Nature and Forest (INBO)",
    datasetID = "7cca70f5-ef8c-4f86-85fb-8f070937d7ab",
    datasetName = "Sample from: MICA - Muskrat and coypu camera trap observations in Belgium, the Netherlands and Germany",
    dataGeneralizations = "coordinates rounded to 0.001 degree") %>% 
  select(type, rightsHolder, datasetID, datasetName, dataGeneralizations, eventID, parentEventID, eventType, eventDate, habitat, samplingProtocol, decimalLatitude, decimalLongitude, geodeticDatum, coordinateUncertaintyInMeters, locationID, locationName)
  
```

## Occurrence Extension:

```{r}
dwc_occurrence_ext <- 
  observations %>% 
# Filter observations on animal observations (excluding humans, blanks, etc.)
  dplyr::filter(.data$observationType == "animal") %>% 
  
# Map to Dwc
  dplyr::mutate(
    .keep = "none",
     occurrenceID = .data$observationID,
    individualCount = .data$count,
    sex = .data$sex,
    lifeStage = .data$lifeStage,
    behavior = .data$behavior,
    occurrenceStatus = "present",
    associatedMedia = case_when(
      is.na(.data$mediaID) ~ "URL 1 | URL 2 | URL 3 | etc.",
      TRUE ~ "URL"
    ),
    eventID = .data$eventID,
    parentEventID = .data$deploymentID,
    identifiedBy = .data$classifiedBy,
    dateIdentified = format(
      .data$classificationTimestamp,
      format = "%Y-%m-%dT%H:%M:%SZ"
    ),
    identificationRemarks = "identificationRemarks",
    scientificName = .data$scientificName,
    kingdom = "Animalia") %>% 
  dplyr::select(occurrenceID, individualCount, sex, lifeStage, behavior, occurrenceStatus, associatedMedia, eventID, parentEventID, identifiedBy,dateIdentified, identificationRemarks, scientificName, kingdom)
```

## Audubon Extension

```{r}
dwc_audubon <- 
  media %>% dplyr::left_join(
   select(observations, mediaID, eventID),
   by = "mediaID"
  ) %>% 
  dplyr::mutate(
    .keep = "none",
    metadataLanguage = "http://id.loc.gov/vocabulary/iso639-2/eng",
    eventID = .data$eventID,
    identifier = .data$mediaID,
    `dc:type` = dplyr::case_when(
      grepl("video", fileMediatype) ~ "MovingImage",
      .default = "StillImage"
      ),
     comments = dplyr::case_when(
        !is.na(favorite) & !is.na(mediaComments)
          ~ paste("marked as favourite", mediaComments, sep = " | "),
        !is.na(favorite) ~ "marked as favourite",
        .default = .data$mediaComments
      ),
     `dcterms:rights` = "http://creativecommons.org/licenses/by/4.0/",
     CreateDate = format(.data$timestamp, format = "%Y-%m-%dT%H:%M:%SZ"),
      captureDevice = "Reconyx-HF2X",
      resourceCreationTechnique = dplyr::recode(
        .data$captureMethod,
        "motionDetection" = "motion detection",
        "timeLapse" = "time lapse"
      ),
     accessURI = .data$filePath,
    `dc:format` = .data$fileMediatype) %>%
  
    # Set column order
    dplyr::select(
      "metadataLanguage", "eventID", "identifier", "dc:type", "comments", "dcterms:rights",
      "CreateDate", "captureDevice", "resourceCreationTechnique", "accessURI",
      "dc:format"
    )


```

## Extended Measurement or Facts extension

```{r}
# eMoF linked to the deployment (parent event)

emof_parent <- 
 deployments %>% gather(
   key = "measurementType",
   value = "measurementValue",
   setupBy, cameraID:detectionDistance,baitUse, deploymentGroups:deploymentComments) %>%  
  select(deploymentID, measurementType, measurementValue) %>% 
  mutate(
   eventID = .data$deploymentID,
   occurrenceID = "") %>% 
  select(eventID, occurrenceID, measurementType, measurementValue)

# eMoF linked to sequence-based observations (event)

emof_event <-
  observations %>% filter(
    .data$observationLevel == "event") %>% 
  gather(
    key = "measurementType",
    value = "measurementValue",
    observationType, individualPositionRadius:classifiedBy) %>% 
  mutate(
    eventID = .data$eventID,
    occurrenceID = .data$observationID) %>% 
  select(eventID, occurrenceID, measurementType, measurementValue)

# eMof linked to media-based observations

emof_media <-
  observations %>% filter(
    .data$observationLevel == "media") %>% 
  gather(
    key = "measurementType",
    value = "measurementValue",
    observationType, individualPositionRadius:classifiedBy) %>% 
  mutate(
    eventID = .data$eventID,
    occurrenceID = .data$observationID) %>% 
  select(eventID, occurrenceID, measurementType, measurementValue)

# Bind dataframes

dwc_emof <- 
  base::rbind(emof_parent, emof_event, emof_media) %>% 
  dplyr::arrange(eventID, occurrenceID)


```
Export datasets:

```{r}
write_csv(dwc_event, here("data", "dwc_event", "event.csv"), na = "")
write_csv(dwc_occurrence_ext, here("data", "dwc_event", "occurrence.csv"), na = "")
write_csv(dwc_audubon, here("data", "dwc_event", "audubon.csv"), na = "")
write_csv(dwc_emof, here("data", "dwc_event", "emof.csv"), na = "")

```






